package api

import (
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"time"

	"github.com/karimkheirat/simsim-pos-agent/internal/capabilities"
	"github.com/karimkheirat/simsim-pos-agent/internal/label"
	"github.com/karimkheirat/simsim-pos-agent/internal/tspl"
)

// printLabelRequest is the body of POST /print-label.
//
// TerminalID is optional and audit-only — the agent's bound terminal
// (from secrets) is the source of truth for routing; we only log the
// client-supplied value when it diverges, to help diagnose
// terminal-mismatch incidents.
type printLabelRequest struct {
	JobID          string      `json:"job_id"`
	IdempotencyKey string      `json:"idempotency_key,omitempty"`
	Label          label.Label `json:"label"`
	TerminalID     string      `json:"terminal_id,omitempty"`
}

// printLabelResponseData is the shape returned inside the {ok,data}
// envelope on success.
type printLabelResponseData struct {
	JobID       string `json:"job_id"`
	PrinterName string `json:"printer_name"`
	BytesSent   int    `json:"bytes_sent"`
	DurationMs  int64  `json:"duration_ms"`
}

// handlePrintLabel renders a Label and submits it to the LABEL
// printer with idempotency keyed on job_id. JWT-authed via
// requireAuth. M13 Track B PR 2.
//
// Pipeline (mirrors handlePrint with label-specific branches):
//  1. Parse + validate body (Label.Validate)
//  2. Idempotency replay — return cached response verbatim if hit
//  3. Resolve label printer (printerForIntent("label") — 503 if absent)
//  4. Capability gate (QR support per LookupLabel)
//  5. Render (label.Render → bytes; honors agent's tspl_dialect)
//  6. Submit to printer (labelPrinter.Print)
//  7. Cache + structured log + write response
func (s *Server) handlePrintLabel(w http.ResponseWriter, r *http.Request) {
	var req printLabelRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, CodeLabelInvalid, "invalid JSON: "+err.Error())
		return
	}
	if req.JobID == "" {
		writeError(w, http.StatusBadRequest, CodeLabelInvalid, "job_id required")
		return
	}

	// 2. Idempotency replay — return cached response verbatim.
	// The idem store is shared with /print; in practice job_ids are
	// generated by the web client per-call so collisions across
	// endpoints don't happen, but a deliberate replay of the same
	// /print-label job_id correctly returns the cached label response.
	if cached, ok := s.idem.Get(req.JobID); ok {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(cached.Status)
		_, _ = w.Write(cached.Body)
		return
	}

	// 1. Validate the label payload (after job_id but before any
	// printer / capability work — cheap and label-specific 400).
	if err := req.Label.Validate(); err != nil {
		writeError(w, http.StatusBadRequest, CodeLabelInvalid, err.Error())
		return
	}

	// 3. Printer resolution.
	p, status, code, message := s.printerForIntent("label")
	if status != 0 {
		writeError(w, status, code, message)
		return
	}

	// 4. Capability gate. LookupLabel returns conservative defaults
	// for an unknown printer name (QRSupported=true), so a real
	// production deployment won't usually trip this — but the gate
	// is the single explicit place capability-vs-template mismatches
	// surface to operators.
	caps := capabilities.LookupLabel(p.Name())
	if !caps.QRSupported && labelContainsQR(req.Label) {
		writeError(w, http.StatusBadRequest, CodeLabelRequiresUnsupportedCapability,
			"label uses qrcode element but printer does not support QR")
		return
	}

	// 5. Render to TSPL bytes. The agent's tspl_dialect (set in
	// config.json, defaulted to "standard") drives the EAN-13
	// hyphen split — Rongta printers get "EAN-13", others get "EAN13".
	data, err := label.Render(req.Label, label.RenderOptions{
		Dialect:     tspl.Dialect(s.cfg.TSPLDialect),
		QRSupported: caps.QRSupported,
	})
	if err != nil {
		// label.Render's ErrQRNotSupported should have been blocked
		// by the gate above, but defensive — surface as the same code
		// for consistency.
		if errors.Is(err, label.ErrQRNotSupported) {
			writeError(w, http.StatusBadRequest, CodeLabelRequiresUnsupportedCapability, err.Error())
			return
		}
		// label.Render also wraps ErrInvalidLabel from per-element
		// failures during dispatch (unknown symbology, type, etc.).
		// Validate caught most of these; defensive map.
		if errors.Is(err, label.ErrInvalidLabel) {
			writeError(w, http.StatusBadRequest, CodeLabelInvalid, err.Error())
			return
		}
		writeError(w, http.StatusInternalServerError, CodeInternal, "render: "+err.Error())
		return
	}

	// 6. Submit to the label printer. We don't gate on IsReachable
	// the same way /print does because the print spooler queues
	// jobs when the device is briefly unavailable — the printer-
	// side error surfaces via Print() if the spool ultimately fails.
	// (Same behaviour shape as /print, kept for parity.)
	if !p.IsReachable() {
		writeError(w, http.StatusServiceUnavailable, CodePrinterOffline, "label printer not reachable")
		return
	}
	jobName := "label-" + req.JobID
	start := time.Now()
	if err := p.Print(jobName, data); err != nil {
		writeError(w, http.StatusInternalServerError, CodeLabelPrintFailed, err.Error())
		return
	}
	duration := time.Since(start)

	// 7. Cache + response + log.
	resp := printLabelResponseData{
		JobID:       req.JobID,
		PrinterName: p.Name(),
		BytesSent:   len(data),
		DurationMs:  duration.Milliseconds(),
	}
	respBody, _ := json.Marshal(envelopeOK{OK: true, Data: resp})

	// Cache BEFORE writing — protects against double-print if the
	// wire write fails after the printer side-effect already
	// committed. Same shape as handlePrint.
	s.idem.Set(req.JobID, Result{
		JobID:  req.JobID,
		Status: http.StatusOK,
		Body:   respBody,
	})

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBody)

	s.logger.Info("print_label success",
		"event", "print_label",
		"terminal_id_request", req.TerminalID,
		"job_id", req.JobID,
		"printer_name", p.Name(),
		"label_size", labelSizeString(req.Label),
		"element_count", len(req.Label.Elements),
		"bytes_sent", len(data),
		"duration_ms", duration.Milliseconds(),
		"success", true,
	)
}

// labelContainsQR reports whether any element in l is a QR code.
// Pulled out so the capability gate stays readable.
func labelContainsQR(l label.Label) bool {
	for _, e := range l.Elements {
		if e.Type == label.ElementQRCode {
			return true
		}
	}
	return false
}

// labelSizeString returns "WxH" mm for structured logging.
func labelSizeString(l label.Label) string {
	return strconv.Itoa(l.Size.Width) + "x" + strconv.Itoa(l.Size.Height) + "mm"
}
